version: '3.7'

services:
  postgres:
    image: postgres:16
    container_name: project_ecommerce_dev
    ports:
      - '${PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - polls_pg_data:/var/lib/postgresql/data
volumes:
  polls_pg_data: